# Generated by Django 5.2.7 on 2025-12-02 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Iphone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('fecha_vencimiento', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Iphone.metodopago'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Iphone.metodopago'),
        ),
    ]
